routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('Panel Principal');
Route::get('/seleccionar/proyecto/{id}', 'HomeController@selectProject');

Route::group(['middleware' => ['auth','permisos']], function(){
	
	//User Profile
	Route::get('/perfil', 'Admin\UserController@profile')->name('Perfil de Usuario');
    Route::post('perfil/{id}', 'Admin\UserController@update_perfil');
	
	//Permits
	Route::get('/permisos', 'Admin\PermitController@index')->name('Permisos');    
	Route::post('/permisos', 'Admin\PermitController@store')->name('permisos.store');
	
	Route::get('/permisos/{id}', 'Admin\PermitController@edit')->name('Editar permisos');
    Route::post('/permisos/{id}', 'Admin\PermitController@update')->name('permisos.update');    

	//Incidents
	//See Incidents
	Route::get('/ver', 'IncidentController@index')->name('Ver incidencias');
	Route::post('/ver/reasignar', 'IncidentController@reassign')->name('ver.reasignar');

	//Report Incident
	Route::get('/reportar', 'IncidentController@create')->name('Reportar incidencias');    
	Route::post('/reportar', 'IncidentController@store')->name('reportar.store');
	//Edit Incident
	Route::get('/incidencia/{id}/editar', 'IncidentController@edit')->name('Editar incidencia');
	Route::post('/incidencia/{id}/editar', 'IncidentController@update')->name('incidencia.update');
	
	//See incident
	Route::get('/ver/{id}', 'IncidentController@show')->name('Ver Detalles de la Incidencia');	
	Route::post('/ver/asignar', 'IncidentController@assign')->name('ver.assign');	
	Route::get('/incidencia/{id}/atender', 'IncidentController@take')->name('ver.take');
	Route::get('/incidencia/{id}/resolver', 'IncidentController@solve')->name('ver.solve');
	Route::get('/incidencia/{id}/abrir', 'IncidentController@open')->name('ver.open');
	Route::get('/incidencia/{id}/derivar', 'IncidentController@nextLevel')->name('ver.nextLevel');

	//Messages
	Route::post('/mensajes',[
		'as' => 'mensajes.store',
		'uses' => 'MessageController@store'
	]);
	/*
	//Calendar Asignament
	Route::get('/calendario', function () {
		return view('calendar');
	});
	*/

	//statistics charts
	Route::get('/estadisticas', 'GraficasController@index')->name('Reportes y Estadisticas');
	Route::get('/estadisticas/{anio}/{mes}', 'GraficasController@registros_mes')->name('reportes.anio.mes');
	Route::get('/estadisticas/incidencias/{anio}/{mes}', 'GraficasController@total_incidencias')->name('estadisticas.incidencias');
	Route::get('/estadisticas/modulos/{anio}/{mes}', 'GraficasController@total_modulos')->name('estadisticas.modulos');

	//User
	Route::get('/usuarios', [
	    'as' => 'Creación de usuarios',
        'uses' => 'Admin\UserController@index'
    ]);
	Route::post('/usuarios', [
		'as' => 'usuarios.store',
		'uses' => 'Admin\UserController@store'
	]);

	Route::get('/usuarios/{id}', [
		'as' => 'Editar usuario',
		'uses' => 'Admin\UserController@edit'
	]);	
	Route::post('/usuarios/{id}', [
		'as' => 'usuarios.update',
		'uses' => 'Admin\UserController@update'
	]);
	Route::get('/usuarios/{id}/eliminar', [
		'as' => 'usuarios.delete',
		'uses' => 'Admin\UserController@delete'
	]);

	//Profiles
	Route::get('/perfiles', [
	    'as' => 'Roles de usuarios',
        'uses' => 'Admin\ProfileController@index'
    ]);
	Route::post('/perfiles', [
		'as' => 'perfiles.store',
		'uses' => 'Admin\ProfileController@store'
	]);
	Route::post('/perfiles/editar', [
		'as' => 'perfiles.update',
		'uses' => 'Admin\ProfileController@update'
	]);
	Route::get('/perfiles/{id}/eliminar', [
		'as' => 'perfiles.delete',
		'uses' => 'Admin\ProfileController@delete'
	]);
	Route::get('/perfiles/{id}/restaurar', [
		'as' => 'perfiles.restore',
		'uses' => 'Admin\ProfileController@restore'
	]);

	//Menu
	Route::get('/opciones', [
	    'as' => 'Menú',
        'uses' => 'Admin\MenuController@index'
    ]);
	Route::post('/opciones', [
		'as' => 'opciones.store',
		'uses' => 'Admin\MenuController@store'
	]);
	Route::get('/opciones/{id}', [
		'as' => 'Editar opciones',
		'uses' => 'Admin\MenuController@edit'
	]);
	Route::post('/opciones/{id}', [
		'as' => 'opciones.update',
		'uses' => 'Admin\MenuController@update'
	]);
	Route::get('/opciones/{id}/eliminar', [
		'as' => 'opciones.delete',
		'uses' => 'Admin\MenuController@delete'
	]);
	Route::get('/opciones/hijos/{id}', [
		'as' => 'opciones.gethijos',
		'uses' => 'Admin\MenuController@gethijos'
	]);

	//Project
	Route::get('/proyectos', [
	    'as' => 'Proyectos',
        'uses' => 'Admin\ProjectController@index'
    ]);
	Route::post('/proyectos', [
		'as' => 'proyectos.store',
		'uses' => 'Admin\ProjectController@store'
	]);
	Route::get('/proyectos/{id}', [
		'as' => 'Editar proyectos',
		'uses' => 'Admin\ProjectController@edit'
	]);
	Route::post('/proyectos/{id}', [
		'as' => 'proyectos.update',
		'uses' => 'Admin\ProjectController@update'
	]);
	Route::get('/proyectos/{id}/eliminar', [
		'as' => 'proyectos.delete',
		'uses' => 'Admin\ProjectController@delete'
	]);
	Route::get('/proyectos/{id}/restaurar', [
		'as' => 'proyectos.restore',
		'uses' => 'Admin\ProjectController@restore'
	]);

	//Category
	Route::post('/categorias', [
		'as' => 'categorias.store',
		'uses' => 'Admin\CategoryController@store'
	]);
	Route::post('/categorias/editar', [
		'as' => 'categorias.update',
		'uses' => 'Admin\CategoryController@update'
	]);
	Route::get('/categorias/{id}/eliminar', [
		'as' => 'categorias.delete',
		'uses' => 'Admin\CategoryController@delete'
	]);	

	//Level
	Route::post('/niveles', [
		'as' => 'niveles.store',
		'uses' => 'Admin\LevelController@store'
	]);
	Route::post('/niveles/editar', [
		'as' => 'niveles.update',
		'uses' => 'Admin\LevelController@update'
	]);
	Route::get('/niveles/{id}/eliminar', [
		'as' => 'niveles.delete',
		'uses' => 'Admin\LevelController@delete'
	]);

	//Project-User
	Route::post('/proyecto-usuario', [
		'as' => 'proyectos_usuario.store',
		'uses' => 'Admin\ProjectUserController@store'
	]);
	Route::get('/proyecto-usuario/{id}/eliminar', [
		'as' => 'proyectos_usuario.delete',
		'uses' => 'Admin\ProjectUserController@delete'
	]);
	/**
	//Config
	Route::get('/config', [
		'as' => 'config.index',
		'uses' => 'ConfigController@index'
	]);	**/
});


Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

app/Incident.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Incident extends Model
{
    //validations
    public static $rules = [
    'category_id' => 'sometimes|exists:categories,id',
    'severity' => 'required|in:M,N,A',
    'title' => 'required|min:5',
    'description' => 'required|min:15'
    ];

    public static $messages = [
        'category_id.exists' => 'La Categoria seleccionada no existe en nuestra base de datos.',
        'title.required' => 'No ha ingresado un titulo para la incidencia.',
        'title.min' => 'El titulo debe tener al menos 5 caracteres.',
        'description.required' => 'Es necesario ingresar una descripción para la incidencia.',
        'description.min' => 'La descripción debe presentar al menos 15 caracteres.'
    ];

    //Relationships

    protected $appends = ['state'];

     public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function level()
    {
    	return $this->belongsTo('App\Level');
    }

    public function project()
    {
    	return $this->belongsTo('App\Project');
    }

    public function support()
    {
    	return $this->belongsTo('App\User', 'support_id');
    }
    
    public function messages()
    {
    	return $this->hasMany('App\Message');
    }

    public function client()
    {
        return $this->belongsTo('App\User', 'client_id');
    }

    public function profile()
    {
        return $this->belongsTo('App\Profile'/*,[client->profile_id]*/);
    }

    //Accesors

    //Severity Name
    public function getSeverityFullAttribute()
    {
    	switch ($this->severity) {
    		case 'M':
    			return 'Menor';
    		case 'N':
    			return 'Normal';   			
    		
    		default:    			
    			return 'Alta';
    	}
    }

    //title short
    public function getTitleShortAttribute()
    {
    	return mb_strimwidth($this->title, 0, 20, '...');
    }

    //Category Name
    public function getCategoryNameAttribute()
    {
        if ($this->category)
            return $this->category->name;
        
        return 'General';
    }

    //Project Name
    public function getProjectNameAttribute()
    {
        if ($this->project)
            return $this->project->name;
    }   
   
    //Support Name
    public function getSupportNameAttribute()
    {
    	if ($this->support)
    		return $this->support->name;
    	
    	return 'Sin asignar';
    }

    //client Name
    public function getClientNameAttribute()
    {
        if ($this->client)
            return $this->client->name;
        
        return 'Sin asignar';
    }

    //Profile Name
    public function getProfileNameAttribute()
    {
        if ($this->client)
            return $this->client->profile_id;
        /*
        if ($this->profile)
            return $this->profile->name;
        */
    }

    public function getAvatarClientAttribute()
    {
        if($this->client)
            return $this->client->avatar;
    }

    //State    
    public function getStateAttribute()
    {
    	if ($this->active == 0)
    		return 'Resuelta';
    	
    	if($this->support_id)
    		return 'Asignado';

    	return 'Pendiente';
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    public static $rules = [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6',
            'profile_id' => 'sometimes|exists:profiles,id',

        ];
    public static $messages = [
        'name.required' => 'Es necesario ingresar el nombre del usuario.',
        'name.max' => 'El nombre es demasiado extenso.',

        'email.required' => 'Es indispensable ingresar el e-mail del usuario.',
        'email.email' => 'El e-mail ingresado no es valido.',
        'email.max' => 'El e-mail es demasiado extenso.',
        'email.unique' => 'Este e-mail ya se encuentra en uso.',

        'password.required' => 'Olvido ingresar la contraseña.',
        'password.min' => 'La contraseña debe presentar al menos 6 caracteres.',
        'profile_id.exists' => 'El perfil seleccionado no existe en nuestra base de datos.',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','profile_id','avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    //Relationships
    
    public function socialProvider()
    {
        return $this->hasMany(socialProvider::class);
    }

    public function projects()
    {
        return $this->belongsToMany('App\Project');
    }

    public function profile()
    {
        return $this->belongsTo('App\Profile');
    }

    public function canTake(Incident $incident)
    {
        return ProjectUser::where('user_id', $this->id)->where('level_id', $incident->level_id)->first();
    }

    

    /**Accessors**/

    //Profile Name
    public function getProfileNameAttribute()
    {
        if ($this->profile)
            return $this->profile->name;
    }
    
    public function getListOfProjectsAttribute()
    {
        if($this->profile_id == 2)
            return $this->projects;
        
        return Project::all();
    }

    public function getIsAdminAttribute()
    {
        return $this->profile_id == 1;
    }

    public function getIsSupportAttribute()
    {
        return $this->profile_id == 2;
    }

    public function getIsClientAttribute()
    {
        return $this->profile_id == 3;
    }

    public function getNameShortAttribute()
    {
        return mb_strimwidth($this->name, 0, 20, '...');
    }
    
    
}

resources/views/home.blade.php
@extends('layouts.app')
@section('head')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">
@endsection
@section('content')

<section class="content-header">
  <h1>
    Dashboard
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">        
    <li class="active">Dashboard</li>
  </ol>
</section>
<section class="content">
  <div class="box-body">
    @if (session('notification-warning'))
    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <i class="icon fa fa-warning"></i> 
        {{ session('notification-warning') }}
    </div>    
    @endif
    <div class="row">
      @if (auth()->user()->is_support)
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Incidencias Asignadas a mí</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="example" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Categoría</th>
                  <th>Severidad</th>
                  <th>Estado</th>
                  <th>Fecha Creación</th>
                  <th>Título</th>
                </tr>
              </thead>
              <tbody id="dashboard_my_incidents">
                @foreach ($my_incidents as $incident)
                <tr>
                  <td style="text-align:center">
                    <a href="/ver/{{ $incident->id }}">
                      {{ $incident->id }}
                    </a>
                  </td>
                  <td>{{ $incident->category->name }}</td>
                  <td>{{ $incident->severity_full }}</td>
                  <td>{{ $incident->state }}</td>
                  <td>{{ $incident->created_at }}</td>
                  <td>{{ $incident->title_short }}</td>                              
                  
                </tr>
                @endforeach                
              </tbody>
              <tfoot>
                <tr>
                  <th>Código</th>
                  <th>Categoría</th>
                  <th>Severidad</th>
                  <th>Estado</th>
                  <th>Fecha Creación</th>
                  <th>Título</th>
                </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Incidencias sin asignar</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="tabla1" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Categoría</th>
                  <th>Severidad</th>
                  <th>Estado</th>
                  <th>Fecha de Creación</th>
                  <th>Título</th>
                  <th>Opción</th>
                </tr>
              </thead>
              <tbody id="dashboard_pending_incidents">
                @foreach ($pending_incidents as $incident)
                <tr>
                  <td style="text-align:center">
                    <a href="/ver/{{ $incident->id }}">
                      {{ $incident->id }}
                    </a>
                  </td>
                  <td>{{ $incident->category->name }}</td>
                  <td>{{ $incident->severity_full }}</td>
                  <td>{{ $incident->state }}</td>
                  <td>{{ $incident->created_at }}</td>
                  <td>{{ $incident->title_short }}</td> 
                  <td style="text-align:center">
                    <a href="/incidencia/{{ $incident->id }}/atender" class="btn btn-sm btn-primary">
                      Atender
                    </a>
                  </td>                               
                </tr>
                @endforeach                                              
              </tbody>
              <tfoot>
                <tr>
                  <th>Código</th>
                  <th>Categoría</th>
                  <th>Severidad</th>
                  <th>Estado</th>
                  <th>Fecha de Creación</th>
                  <th>Título</th>
                  <th>Opción</th>
                </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
      @endif
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Incidencias reportadas por mi</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="tabla2" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Código</th>
                  <th>Categoría</th>
                  <th>Severidad</th>
                  <th>Estado</th>
                  <th>Fecha Creación</th>
                  <th>Título</th>                 
                  <th>Responsable</th>
                </tr>
              </thead>
              <tbody id="dashboard_by_me">
                @foreach ($incidents_by_me as $incident)
                <tr>
                  <td style="text-align:center">
                    <a href="/ver/{{ $incident->id }}">
                      {{ $incident->id }}
                    </a>
                  </td>
                  <td>{{ $incident->category_name }}</td>
                  <td>{{ $incident->severity_full }}</td>
                  <td>{{ $incident->state }}</td>
                  <td>{{ $incident->created_at }}</td>
                  <td>{{ $incident->title_short }}</td>
                  <td>{{ $incident->support_name }}</td>
                </tr>
                @endforeach                                                       
              </tbody>
              <tfoot>
                <tr>
                  <th>Código</th>
                  <th>Categoría</th>
                  <th>Severidad</th>
                  <th>Estado</th>
                  <th>Fecha Creación</th>
                  <th>Título</th>                 
                  <th>Responsable</th>
                </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
  </div>
</section>


@endsection
@section('scripts')
  
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>



  <script type="text/javascript">

    $('#example').DataTable( {
      dom: 'Bfrtip',
      buttons: [
      'copyHtml5', 'excelHtml5', 'pdfHtml5', 'csvHtml5', 'print'
      ]
    } );
    $('#tabla1').DataTable( {
      dom: 'Bfrtip',
      buttons: [
      'copyHtml5', 'excelHtml5', 'pdfHtml5', 'csvHtml5', 'print'
      ]
    } );
    $('#tabla2').DataTable( {
      dom: 'Bfrtip',
      buttons: [
      'copyHtml5', 'excelHtml5', 'pdfHtml5', 'csvHtml5', 'print'
      ]
    } );

  </script>
  @endsection

resources/views/newmail.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Mailbox
    <small>13 new messages</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Mailbox</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-3">
      <a href="/correo" class="btn btn-primary btn-block margin-bottom">Back to Inbox</a>

      <div class="box box-solid">
        <div class="box-header with-border">
          <h3 class="box-title">Folders</h3>

          <div class="box-tools">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="box-body no-padding">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="/correo"><i class="fa fa-inbox"></i> Inbox
              <span class="label label-primary pull-right">12</span></a></li>
              <li><a href="#"><i class="fa fa-envelope-o"></i> Sent</a></li>
              <li><a href="#"><i class="fa fa-file-text-o"></i> Drafts</a></li>
              <li><a href="#"><i class="fa fa-filter"></i> Junk <span class="label label-warning pull-right">65</span></a>
              </li>
              <li><a href="#"><i class="fa fa-trash-o"></i> Trash</a></li>
            </ul>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /. box -->
        <div class="box box-solid">
          <div class="box-header with-border">
            <h3 class="box-title">Labels</h3>

            <div class="box-tools">
              <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
              </button>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body no-padding">
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#"><i class="fa fa-circle-o text-red"></i> Important</a></li>
              <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> Promotions</a></li>
              <li><a href="#"><i class="fa fa-circle-o text-light-blue"></i> Social</a></li>
            </ul>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
      <div class="col-md-9">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Compose New Message</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <div class="form-group">
              <input class="form-control" placeholder="To:">
            </div>
            <div class="form-group">
              <input class="form-control" placeholder="Subject:">
            </div>
            <div class="form-group">
              <textarea id="compose-textarea" class="form-control" style="height: 300px">
                <h1><u>Heading Of Message</u></h1>
                <h4>Subheading</h4>
                <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain
                  was born and I will give you a complete account of the system, and expound the actual teachings
                  of the great explorer of the truth, the master-builder of human happiness. No one rejects,
                  dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know
                  how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again
                  is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain,
                  but because occasionally circumstances occur in which toil and pain can procure him some great
                  pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise,
                  except to obtain some advantage from it? But who has any right to find fault with a man who
                  chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that
                  produces no resultant pleasure? On the other hand, we denounce with righteous indignation and
                  dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so
                blinded by desire, that they cannot foresee</p>
                <ul>
                  <li>List item one</li>
                  <li>List item two</li>
                  <li>List item three</li>
                  <li>List item four</li>
                </ul>
                <p>Thank you,</p>
                <p>John Doe</p>
              </textarea>
            </div>
            <div class="form-group">
              <div class="btn btn-default btn-file">
                <i class="fa fa-paperclip"></i> Attachment
                <input type="file" name="attachment">
              </div>
              <p class="help-block">Max. 32MB</p>
            </div>
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <div class="pull-right">
              <button type="button" class="btn btn-default"><i class="fa fa-pencil"></i> Draft</button>
              <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send</button>
            </div>
            <button type="reset" class="btn btn-default"><i class="fa fa-times"></i> Discard</button>
          </div>
          <!-- /.box-footer -->
        </div>
        <!-- /. box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
  @endsection

  @section('scripts')
  <!-- Page Script -->
  <script>
    $(function () {
      //Add text editor
      $("#compose-textarea").wysihtml5();
    });
  </script>
  @endsection