routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('Panel Principal');
Route::get('/seleccionar/proyecto/{id}', 'HomeController@selectProject');

Route::group(['middleware' => ['auth','permisos']], function(){
	
	//User Profile
	Route::get('/perfil', 'Admin\UserController@profile')->name('Perfil de Usuario');
    Route::post('perfil/{id}', 'Admin\UserController@update_perfil');
	
	//Permits
	Route::get('/permisos', 'Admin\PermitController@index')->name('Permisos');    
	Route::post('/permisos', 'Admin\PermitController@store')->name('permisos.store');
	
	Route::get('/permisos/{id}', 'Admin\PermitController@edit')->name('Editar permisos');
    Route::post('/permisos/{id}', 'Admin\PermitController@update')->name('permisos.update');    

	//Incidents
	//See Incidents
	Route::get('/ver', 'IncidentController@index')->name('Ver incidencias');
	Route::post('/ver/reasignar', 'IncidentController@reassign')->name('ver.reasignar');

	//Report Incident
	Route::get('/reportar', 'IncidentController@create')->name('Reportar incidencias');    
	Route::post('/reportar', 'IncidentController@store')->name('reportar.store');
	//Edit Incident
	Route::get('/incidencia/{id}/editar', 'IncidentController@edit')->name('Editar incidencia');
	Route::post('/incidencia/{id}/editar', 'IncidentController@update')->name('incidencia.update');
	
	//See incident
	Route::get('/ver/{id}', 'IncidentController@show')->name('Ver Detalles de la Incidencia');	
	Route::post('/ver/asignar', 'IncidentController@assign')->name('ver.assign');	
	Route::get('/incidencia/{id}/atender', 'IncidentController@take')->name('ver.take');
	Route::get('/incidencia/{id}/resolver', 'IncidentController@solve')->name('ver.solve');
	Route::get('/incidencia/{id}/abrir', 'IncidentController@open')->name('ver.open');
	Route::get('/incidencia/{id}/derivar', 'IncidentController@nextLevel')->name('ver.nextLevel');

	//Messages
	Route::post('/mensajes',[
		'as' => 'mensajes.store',
		'uses' => 'MessageController@store'
	]);
	/*
	//Calendar Asignament
	Route::get('/calendario', function () {
		return view('calendar');
	});
	*/

	//statistics charts
	Route::get('/estadisticas', 'GraficasController@index')->name('Reportes y Estadisticas');
	Route::get('/estadisticas/{anio}/{mes}', 'GraficasController@registros_mes')->name('reportes.anio.mes');
	Route::get('/estadisticas/incidencias/{anio}/{mes}', 'GraficasController@total_incidencias')->name('estadisticas.incidencias');
	Route::get('/estadisticas/modulos/{anio}/{mes}', 'GraficasController@total_modulos')->name('estadisticas.modulos');

	//User
	Route::get('/usuarios', [
	    'as' => 'Creación de usuarios',
        'uses' => 'Admin\UserController@index'
    ]);
	Route::post('/usuarios', [
		'as' => 'usuarios.store',
		'uses' => 'Admin\UserController@store'
	]);

	Route::get('/usuarios/{id}', [
		'as' => 'Editar usuario',
		'uses' => 'Admin\UserController@edit'
	]);	
	Route::post('/usuarios/{id}', [
		'as' => 'usuarios.update',
		'uses' => 'Admin\UserController@update'
	]);
	Route::get('/usuarios/{id}/eliminar', [
		'as' => 'usuarios.delete',
		'uses' => 'Admin\UserController@delete'
	]);

	//Profiles
	Route::get('/perfiles', [
	    'as' => 'Roles de usuarios',
        'uses' => 'Admin\ProfileController@index'
    ]);
	Route::post('/perfiles', [
		'as' => 'perfiles.store',
		'uses' => 'Admin\ProfileController@store'
	]);
	Route::post('/perfiles/editar', [
		'as' => 'perfiles.update',
		'uses' => 'Admin\ProfileController@update'
	]);
	Route::get('/perfiles/{id}/eliminar', [
		'as' => 'perfiles.delete',
		'uses' => 'Admin\ProfileController@delete'
	]);
	Route::get('/perfiles/{id}/restaurar', [
		'as' => 'perfiles.restore',
		'uses' => 'Admin\ProfileController@restore'
	]);

	//Menu
	Route::get('/opciones', [
	    'as' => 'Menú',
        'uses' => 'Admin\MenuController@index'
    ]);
	Route::post('/opciones', [
		'as' => 'opciones.store',
		'uses' => 'Admin\MenuController@store'
	]);
	Route::get('/opciones/{id}', [
		'as' => 'Editar opciones',
		'uses' => 'Admin\MenuController@edit'
	]);
	Route::post('/opciones/{id}', [
		'as' => 'opciones.update',
		'uses' => 'Admin\MenuController@update'
	]);
	Route::get('/opciones/{id}/eliminar', [
		'as' => 'opciones.delete',
		'uses' => 'Admin\MenuController@delete'
	]);
	Route::get('/opciones/hijos/{id}', [
		'as' => 'opciones.gethijos',
		'uses' => 'Admin\MenuController@gethijos'
	]);

	//Project
	Route::get('/proyectos', [
	    'as' => 'Proyectos',
        'uses' => 'Admin\ProjectController@index'
    ]);
	Route::post('/proyectos', [
		'as' => 'proyectos.store',
		'uses' => 'Admin\ProjectController@store'
	]);
	Route::get('/proyectos/{id}', [
		'as' => 'Editar proyectos',
		'uses' => 'Admin\ProjectController@edit'
	]);
	Route::post('/proyectos/{id}', [
		'as' => 'proyectos.update',
		'uses' => 'Admin\ProjectController@update'
	]);
	Route::get('/proyectos/{id}/eliminar', [
		'as' => 'proyectos.delete',
		'uses' => 'Admin\ProjectController@delete'
	]);
	Route::get('/proyectos/{id}/restaurar', [
		'as' => 'proyectos.restore',
		'uses' => 'Admin\ProjectController@restore'
	]);

	//Category
	Route::post('/categorias', [
		'as' => 'categorias.store',
		'uses' => 'Admin\CategoryController@store'
	]);
	Route::post('/categorias/editar', [
		'as' => 'categorias.update',
		'uses' => 'Admin\CategoryController@update'
	]);
	Route::get('/categorias/{id}/eliminar', [
		'as' => 'categorias.delete',
		'uses' => 'Admin\CategoryController@delete'
	]);	

	//Level
	Route::post('/niveles', [
		'as' => 'niveles.store',
		'uses' => 'Admin\LevelController@store'
	]);
	Route::post('/niveles/editar', [
		'as' => 'niveles.update',
		'uses' => 'Admin\LevelController@update'
	]);
	Route::get('/niveles/{id}/eliminar', [
		'as' => 'niveles.delete',
		'uses' => 'Admin\LevelController@delete'
	]);

	//Project-User
	Route::post('/proyecto-usuario', [
		'as' => 'proyectos_usuario.store',
		'uses' => 'Admin\ProjectUserController@store'
	]);
	Route::get('/proyecto-usuario/{id}/eliminar', [
		'as' => 'proyectos_usuario.delete',
		'uses' => 'Admin\ProjectUserController@delete'
	]);
	/**
	//Config
	Route::get('/config', [
		'as' => 'config.index',
		'uses' => 'ConfigController@index'
	]);	**/
});


Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

app/Incident.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Incident extends Model
{
    //validations
    public static $rules = [
    'category_id' => 'sometimes|exists:categories,id',
    'severity' => 'required|in:M,N,A',
    'title' => 'required|min:5',
    'description' => 'required|min:15'
    ];

    public static $messages = [
        'category_id.exists' => 'La Categoria seleccionada no existe en nuestra base de datos.',
        'title.required' => 'No ha ingresado un titulo para la incidencia.',
        'title.min' => 'El titulo debe tener al menos 5 caracteres.',
        'description.required' => 'Es necesario ingresar una descripción para la incidencia.',
        'description.min' => 'La descripción debe presentar al menos 15 caracteres.'
    ];

    //Relationships

    protected $appends = ['state'];

     public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function level()
    {
    	return $this->belongsTo('App\Level');
    }

    public function project()
    {
    	return $this->belongsTo('App\Project');
    }

    public function support()
    {
    	return $this->belongsTo('App\User', 'support_id');
    }
    
    public function messages()
    {
    	return $this->hasMany('App\Message');
    }

    public function client()
    {
        return $this->belongsTo('App\User', 'client_id');
    }

    public function profile()
    {
        return $this->belongsTo('App\Profile'/*,[client->profile_id]*/);
    }

    //Accesors

    //Severity Name
    public function getSeverityFullAttribute()
    {
    	switch ($this->severity) {
    		case 'M':
    			return 'Menor';
    		case 'N':
    			return 'Normal';   			
    		
    		default:    			
    			return 'Alta';
    	}
    }

    //title short
    public function getTitleShortAttribute()
    {
    	return mb_strimwidth($this->title, 0, 20, '...');
    }

    //Category Name
    public function getCategoryNameAttribute()
    {
        if ($this->category)
            return $this->category->name;
        
        return 'General';
    }

    //Project Name
    public function getProjectNameAttribute()
    {
        if ($this->project)
            return $this->project->name;
    }   
   
    //Support Name
    public function getSupportNameAttribute()
    {
    	if ($this->support)
    		return $this->support->name;
    	
    	return 'Sin asignar';
    }

    //client Name
    public function getClientNameAttribute()
    {
        if ($this->client)
            return $this->client->name;
        
        return 'Sin asignar';
    }

    //Profile Name
    public function getProfileNameAttribute()
    {
        if ($this->client)
            return $this->client->profile_id;
        /*
        if ($this->profile)
            return $this->profile->name;
        */
    }

    public function getAvatarClientAttribute()
    {
        if($this->client)
            return $this->client->avatar;
    }

    //State    
    public function getStateAttribute()
    {
    	if ($this->active == 0)
    		return 'Resuelta';
    	
    	if($this->support_id)
    		return 'Asignado';

    	return 'Pendiente';
    }
}

resources/views/incidents/create.blade.php
@extends('layouts.app')

@section('content')

<section class="content-header">
  <h1>
    Reportar Incidencia
    <small>Crear Incidencia</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Reportar Incidencia</li>
  </ol>
</section>
<section class="content">
  <div class="panel-body">
    @if (session('notification'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-check"></i>
      {{ session('notification') }}        
    </div>      
    @endif
    @if (count($errors) > 0)
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><i class="icon fa fa-ban"></i> Alert!</h4>
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>  
    </div>      
    @endif
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Crear Incidencia</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <form action="" method="POST">
        {{ csrf_field() }}
        <div class="box-body">

          <div class="form-group">
            <label for="category_id">Modulo:</label>
            <select name="category_id" class="form-control select2" style="width: 100%;">
              <option value="">Seleccione una opción</option>                      
              @foreach ($categories as $category)                                           
              <option value="{{ $category->id }}">{{ $category->name }}</option>
              @endforeach
            </select>
          </div>

          <div class="form-group">
            <label for="severity">Severidad:</label>
            <select name="severity" class="form-control select2" style="width: 100%;">
              <option value="M">Menor</option>
              <option value="N">Normal</option>
              <option value="A">Alta</option>
            </select>
          </div>                 
          
          <div class="form-group">
            <label for="title">Titulo:</label>
            <input type="text" name="title" class="form-control" placeholder="Escriba un titulo aqui..." value="{{ old('title') }}">
          </div> 

          <div class="form-group">
            <label for="description">Descripcion:</label>
            <textarea name="description" class="form-control" placeholder="Escriba una breve descripción..."></textarea>
          </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          @if (auth()->user()->selected_project_id == null)
          <a class="btn btn-primary disabled"">
            <i class="fa fa-plus-circle"></i>
          Registrar Incidencia</a>
          @else
          <button class="btn btn-primary">
            <i class="fa fa-plus-circle"></i>
            Registrar Incidencia
          </button>
          @endif
        </div>
      </form>
    </div>
  </div>
</section>
@endsection

resources/views/incidents/edit.blade.php
@extends('layouts.app')

@section('content')

<section class="content-header">
  <h1>
    Reportar Incidencia
    <small>Editar Incidencia</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Editar Incidencia</li>
  </ol>
</section>
<section class="content">
  <div class="panel-body">
    @if (session('notification'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-check"></i>
      {{ session('notification') }}        
    </div>      
    @endif
    @if (count($errors) > 0)
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><i class="icon fa fa-ban"></i> Alert!</h4>
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>  
    </div>      
    @endif
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Editar Incidencia</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <form action="" method="POST">
        {{ csrf_field() }}
        <div class="box-body">

          <div class="form-group">
            <label for="category_id">Modulo:</label>
            <select name="category_id" class="form-control">
              <option value="">General</option>
              
            </select>
            
          </div>
          <div class="form-group">
            <label for="severity">Severidad:</label>
            <select name="severity" class="form-control">
              <option value="M" @if($incident->severity == 'M') selected @endif>
                Menor
              </option>
              <option value="N" @if($incident->severity == 'N') selected @endif>
                Normal
              </option>
              <option value="A" @if($incident->severity == 'A') selected @endif>
                Alta
              </option>                    
            </select>
          </div>
          <div class="form-group">
            <label for="title">Titulo:</label>
            <input type="text" name="title" class="form-control" value="{{ old('title', $incident->title) }}">
          </div>                
          <div class="form-group">
            <label for="description">Descripcion:</label>
            <textarea name="description" class="form-control">
              {{ old('description', $incident->description) }}
            </textarea>
          </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button class="btn btn-primary">
            <i class="fa fa-save"></i>
            Guardar Cambios
          </button>
        </div>
      </form>
    </div>
  </div>
</section>


@endsection

resources/views/incidents/index.blade.php
@extends('layouts.app')
@section('head')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">
@endsection
@section('content')

<section class="content-header">
  <h1>
    Incidencias
    <small>Ver Incidencias</small>
  </h1>
  <ol class="breadcrumb">        
    <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"> Ver incidencias</li>
  </ol>
</section>
<section class="content">
  @if (session('notification'))
  <div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <i class="icon fa fa-check"></i>
    {{ session('notification') }}        
  </div>      
  @endif
  @if (count($errors) > 0)
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4><i class="icon fa fa-ban"></i> Alert!</h4>
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>  
  </div>      
  @endif
  <div class="box-body">
    <div class="row">
     
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Incidencias reportadas</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <table id="example" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Código</th>                    
                  <th>Modulo</th>
                  <th>Severidad</th>
                  <th>Estado</th>
                  <th>Fecha Creación</th>
                  <th>Título</th>
                  <th>Reportada por</th>
                  <th>Responsable</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($incidents as $incident)
                <tr>
                  <td style="text-align:center">
                    <a href="/ver/{{ $incident->id }}">
                      {{ $incident->id }}
                    </a>
                  </td>                      
                  <td>{{ $incident->category_name }}</td>
                  <td>{{ $incident->severity_full }}</td>
                  <td>{{ $incident->state }}</td>
                  <td>{{ $incident->created_at }}</td>
                  <td>{{ $incident->title_short }}</td>
                  <td>{{ $incident->client_name }} - {{ $incident->profile_name }}</td>
                  <td>{{ $incident->support_name }}</td>
                  <td style="text-align:center">
                    @if($incident->support_id == null)                        
                    <button  type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modalAssignIncident" title="Asignar incidencia" data-incident="{{ $incident->id }}">                          
                      Asignar
                    </button>                      
                    @else
                    <button  type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#modalAssignIncident" title="Reasignar incidencia" data-incident="{{ $incident->id }}">                          
                      Reasignar
                    </button>
                    @endif
                  </td>                      
                </tr>
                @endforeach                
              </tbody>
              <tfoot>
                <tr>
                  <th>Código</th>                    
                  <th>Modulo</th>
                  <th>Severidad</th>
                  <th>Estado</th>
                  <th>Fecha Creación</th>
                  <th>Título</th>
                  <th>Reportada por</th>
                  <th>Responsable</th>
                  <th>Opciones</th>
                </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
  </div>
</section>

<div class="modal fade" id="modalAssignIncident">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Asignar a:</h4>
        </div>
        <form action="/ver/asignar" method="POST">
          {{ csrf_field() }}
          <div class="modal-body">
            <input type="hidden" name="incident_id" id="incident_id" value="incident_id">         
            <div class="form-group">
              <label for="support_id">Seleccione el usuario a asignar:</label>            
              <select name="support_id" id="support_id" class="form-control select2" style="width: 100%;">
                <option value="0">Seleccione una opción</option>                      
                @foreach ($users as $user)                                           
                <option value="{{ $user->id }}" @if($user->id) selected @endif>{{ $user->name }}</option>
                @endforeach
              </select>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-primary">Asignar</button>
          </div>
        </form>
      </div>
      <!-- /.modal-content -->
    </div>

    <!-- /.modal-dialog -->
  </div>
  @endsection
  @section('scripts')
  <script src="/js/admin/incidents/assign.js"></script>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>



  <script type="text/javascript">

    $('#example').DataTable( {
      dom: 'Bfrtip',
      buttons: [
      'copyHtml5', 'excelHtml5', 'pdfHtml5', 'csvHtml5', 'print'
      ]
    } );

  </script>
  @endsection

resources/views/incidents/show.blade.php
@extends('layouts.app')
@section('content')
<section class="content-header">
    <h1>Reportar Incidencia<small>Ver Incidencia</small></h1>
    <ol class="breadcrumb">
        <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Ver Incidencia</li>
    </ol>
</section>
<section class="content">    
    <div class="panel-body">
        @if (session('notification-warning'))
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="icon fa fa-warning"></i> 
            {{ session('notification-warning') }}
        </div>    
        @endif    
        <div class="box box-primary">    
            <div class="box-header with-border">
              <h3 class="box-title">Ver Detalles de la Incidencia</h3>
            </div>
            <div class="box-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="text-align:center">Código</th>
                            <th style="text-align:center">Proyecto</th>
                            <th style="text-align:center">Categoría</th>
                            <th style="text-align:center">Fecha de envío</th>
                        </tr>                            
                    </thead>
                    <tbody>
                        <tr>
                            <td style="text-align:center" id="incident_key">{{ $incident->id }}</td>
                            <td style="text-align:center" id="incident_project">{{ $incident->project_name }}</td>
                            <td style="text-align:center" id="incident_category">{{ $incident->category_name }}</td>
                            <td style="text-align:center" id="incident_created_at">{{ $incident->created_at }}</td>                        
                        </tr>
                    </tbody>
                    <thead>
                        <tr>
                            <th style="text-align:center">Asignada a</th>
                            <th style="text-align:center">Nivel</th>
                            <th style="text-align:center">Estado</th>
                            <th style="text-align:center">Severidad</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="text-align:center" id="incident_responsible">{{ $incident->support_name }}</td>
                            <td style="text-align:center">{{ $incident->level->name }}</td>
                            <td style="text-align:center" id="incident_state">{{ $incident->state }}</td>
                            <td style="text-align:center" id="incident_severity">{{ $incident->severity_full }}</td>
                        </tr>
                    </tbody>
                </table>
                <br>
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <th>Título</th>
                            <td>{{ $incident->title }}</td>
                        </tr>
                        <tr>
                            <th>Descripcion</th>
                            <td>{{ $incident->description }}</td>
                        </tr>
                        <tr>
                            <th>Adjuntos</th>
                            <td>No se han adjuntado archivos</td>
                        </tr>
                    </tbody>
                </table>
                <br>
                @if ($incident->support_id == null && $incident->active && auth()->user()->canTake($incident))
                <a href="/incidencia/{{ $incident->id }}/atender" class="btn btn-primary" id="incident_btn_apply">
                    Atender incidencia
                </a>
                @endif
                @if (auth()->user()->id == $incident->client_id)
                    @if($incident->active)
                    <a href="/incidencia/{{ $incident->id }}/resolver" class="btn btn-success" id="incident_btn_apply">
                        Marcar como Resuelta
                    </a>
                    <a href="/incidencia/{{ $incident->id }}/editar" class="btn btn-info" id="incident_btn_apply">
                        Editar incidencia
                    </a>

                    @else
                    <a href="/incidencia/{{ $incident->id }}/abrir" class="btn bg-orange" id="incident_btn_apply">
                        Volver a abrir incidencia
                    </a>  
                    @endif
                @endif
                @if (auth()->user()->id == $incident->support_id && $incident->active)
                <a href="/incidencia/{{ $incident->id }}/derivar"class="btn btn-danger" id="incident_btn_apply">
                    Derivar al siguiente nivel
                </a>
                @endif
            </div>
        </div>    
    </div>  
@include('layouts.chat')  
</section>
@endsection