routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('Panel Principal');
Route::get('/seleccionar/proyecto/{id}', 'HomeController@selectProject');

Route::group(['middleware' => ['auth','permisos']], function(){
	
	//User Profile
	Route::get('/perfil', 'Admin\UserController@profile')->name('Perfil de Usuario');
    Route::post('perfil/{id}', 'Admin\UserController@update_perfil');
	
	//Permits
	Route::get('/permisos', 'Admin\PermitController@index')->name('Permisos');    
	Route::post('/permisos', 'Admin\PermitController@store')->name('permisos.store');
	
	Route::get('/permisos/{id}', 'Admin\PermitController@edit')->name('Editar permisos');
    Route::post('/permisos/{id}', 'Admin\PermitController@update')->name('permisos.update');    

	//Incidents
	//See Incidents
	Route::get('/ver', 'IncidentController@index')->name('Ver incidencias');
	Route::post('/ver/reasignar', 'IncidentController@reassign')->name('ver.reasignar');

	//Report Incident
	Route::get('/reportar', 'IncidentController@create')->name('Reportar incidencias');    
	Route::post('/reportar', 'IncidentController@store')->name('reportar.store');
	//Edit Incident
	Route::get('/incidencia/{id}/editar', 'IncidentController@edit')->name('Editar incidencia');
	Route::post('/incidencia/{id}/editar', 'IncidentController@update')->name('incidencia.update');
	
	//See incident
	Route::get('/ver/{id}', 'IncidentController@show')->name('Ver Detalles de la Incidencia');	
	Route::post('/ver/asignar', 'IncidentController@assign')->name('ver.assign');	
	Route::get('/incidencia/{id}/atender', 'IncidentController@take')->name('ver.take');
	Route::get('/incidencia/{id}/resolver', 'IncidentController@solve')->name('ver.solve');
	Route::get('/incidencia/{id}/abrir', 'IncidentController@open')->name('ver.open');
	Route::get('/incidencia/{id}/derivar', 'IncidentController@nextLevel')->name('ver.nextLevel');

	//Messages
	Route::post('/mensajes',[
		'as' => 'mensajes.store',
		'uses' => 'MessageController@store'
	]);
	/*
	//Calendar Asignament
	Route::get('/calendario', function () {
		return view('calendar');
	});
	*/

	//statistics charts
	Route::get('/estadisticas', 'GraficasController@index')->name('Reportes y Estadisticas');
	Route::get('/estadisticas/{anio}/{mes}', 'GraficasController@registros_mes')->name('reportes.anio.mes');
	Route::get('/estadisticas/incidencias/{anio}/{mes}', 'GraficasController@total_incidencias')->name('estadisticas.incidencias');
	Route::get('/estadisticas/modulos/{anio}/{mes}', 'GraficasController@total_modulos')->name('estadisticas.modulos');

	//User
	Route::get('/usuarios', [
	    'as' => 'Creación de usuarios',
        'uses' => 'Admin\UserController@index'
    ]);
	Route::post('/usuarios', [
		'as' => 'usuarios.store',
		'uses' => 'Admin\UserController@store'
	]);

	Route::get('/usuarios/{id}', [
		'as' => 'Editar usuario',
		'uses' => 'Admin\UserController@edit'
	]);	
	Route::post('/usuarios/{id}', [
		'as' => 'usuarios.update',
		'uses' => 'Admin\UserController@update'
	]);
	Route::get('/usuarios/{id}/eliminar', [
		'as' => 'usuarios.delete',
		'uses' => 'Admin\UserController@delete'
	]);

	//Profiles
	Route::get('/perfiles', [
	    'as' => 'Roles de usuarios',
        'uses' => 'Admin\ProfileController@index'
    ]);
	Route::post('/perfiles', [
		'as' => 'perfiles.store',
		'uses' => 'Admin\ProfileController@store'
	]);
	Route::post('/perfiles/editar', [
		'as' => 'perfiles.update',
		'uses' => 'Admin\ProfileController@update'
	]);
	Route::get('/perfiles/{id}/eliminar', [
		'as' => 'perfiles.delete',
		'uses' => 'Admin\ProfileController@delete'
	]);
	Route::get('/perfiles/{id}/restaurar', [
		'as' => 'perfiles.restore',
		'uses' => 'Admin\ProfileController@restore'
	]);

	//Menu
	Route::get('/opciones', [
	    'as' => 'Menú',
        'uses' => 'Admin\MenuController@index'
    ]);
	Route::post('/opciones', [
		'as' => 'opciones.store',
		'uses' => 'Admin\MenuController@store'
	]);
	Route::get('/opciones/{id}', [
		'as' => 'Editar opciones',
		'uses' => 'Admin\MenuController@edit'
	]);
	Route::post('/opciones/{id}', [
		'as' => 'opciones.update',
		'uses' => 'Admin\MenuController@update'
	]);
	Route::get('/opciones/{id}/eliminar', [
		'as' => 'opciones.delete',
		'uses' => 'Admin\MenuController@delete'
	]);
	Route::get('/opciones/hijos/{id}', [
		'as' => 'opciones.gethijos',
		'uses' => 'Admin\MenuController@gethijos'
	]);

	//Project
	Route::get('/proyectos', [
	    'as' => 'Proyectos',
        'uses' => 'Admin\ProjectController@index'
    ]);
	Route::post('/proyectos', [
		'as' => 'proyectos.store',
		'uses' => 'Admin\ProjectController@store'
	]);
	Route::get('/proyectos/{id}', [
		'as' => 'Editar proyectos',
		'uses' => 'Admin\ProjectController@edit'
	]);
	Route::post('/proyectos/{id}', [
		'as' => 'proyectos.update',
		'uses' => 'Admin\ProjectController@update'
	]);
	Route::get('/proyectos/{id}/eliminar', [
		'as' => 'proyectos.delete',
		'uses' => 'Admin\ProjectController@delete'
	]);
	Route::get('/proyectos/{id}/restaurar', [
		'as' => 'proyectos.restore',
		'uses' => 'Admin\ProjectController@restore'
	]);

	//Category
	Route::post('/categorias', [
		'as' => 'categorias.store',
		'uses' => 'Admin\CategoryController@store'
	]);
	Route::post('/categorias/editar', [
		'as' => 'categorias.update',
		'uses' => 'Admin\CategoryController@update'
	]);
	Route::get('/categorias/{id}/eliminar', [
		'as' => 'categorias.delete',
		'uses' => 'Admin\CategoryController@delete'
	]);	

	//Level
	Route::post('/niveles', [
		'as' => 'niveles.store',
		'uses' => 'Admin\LevelController@store'
	]);
	Route::post('/niveles/editar', [
		'as' => 'niveles.update',
		'uses' => 'Admin\LevelController@update'
	]);
	Route::get('/niveles/{id}/eliminar', [
		'as' => 'niveles.delete',
		'uses' => 'Admin\LevelController@delete'
	]);

	//Project-User
	Route::post('/proyecto-usuario', [
		'as' => 'proyectos_usuario.store',
		'uses' => 'Admin\ProjectUserController@store'
	]);
	Route::get('/proyecto-usuario/{id}/eliminar', [
		'as' => 'proyectos_usuario.delete',
		'uses' => 'Admin\ProjectUserController@delete'
	]);
	/**
	//Config
	Route::get('/config', [
		'as' => 'config.index',
		'uses' => 'ConfigController@index'
	]);	**/
});


Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    public static $rules = [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6',
            'profile_id' => 'sometimes|exists:profiles,id',

        ];
    public static $messages = [
        'name.required' => 'Es necesario ingresar el nombre del usuario.',
        'name.max' => 'El nombre es demasiado extenso.',

        'email.required' => 'Es indispensable ingresar el e-mail del usuario.',
        'email.email' => 'El e-mail ingresado no es valido.',
        'email.max' => 'El e-mail es demasiado extenso.',
        'email.unique' => 'Este e-mail ya se encuentra en uso.',

        'password.required' => 'Olvido ingresar la contraseña.',
        'password.min' => 'La contraseña debe presentar al menos 6 caracteres.',
        'profile_id.exists' => 'El perfil seleccionado no existe en nuestra base de datos.',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','profile_id','avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    //Relationships
    
    public function socialProvider()
    {
        return $this->hasMany(socialProvider::class);
    }

    public function projects()
    {
        return $this->belongsToMany('App\Project');
    }

    public function profile()
    {
        return $this->belongsTo('App\Profile');
    }

    public function canTake(Incident $incident)
    {
        return ProjectUser::where('user_id', $this->id)->where('level_id', $incident->level_id)->first();
    }

    

    /**Accessors**/

    //Profile Name
    public function getProfileNameAttribute()
    {
        if ($this->profile)
            return $this->profile->name;
    }
    
    public function getListOfProjectsAttribute()
    {
        if($this->profile_id == 2)
            return $this->projects;
        
        return Project::all();
    }

    public function getIsAdminAttribute()
    {
        return $this->profile_id == 1;
    }

    public function getIsSupportAttribute()
    {
        return $this->profile_id == 2;
    }

    public function getIsClientAttribute()
    {
        return $this->profile_id == 3;
    }

    public function getNameShortAttribute()
    {
        return mb_strimwidth($this->name, 0, 20, '...');
    }
    
    
}

resources/views/partials/config.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-user bg-yellow"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

              <p>New phone +1(800)555-1234</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

              <p>nora@example.com</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-file-code-o bg-green"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

              <p>Execution time 5 seconds</p>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="label label-danger pull-right">70%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Update Resume
              <span class="label label-success pull-right">95%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-success" style="width: 95%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Laravel Integration
              <span class="label label-warning pull-right">50%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Back End Framework
              <span class="label label-primary pull-right">68%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Some information about this general settings option
          </p>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Allow mail redirect
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Other sets of options are available
          </p>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Expose author name in posts
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Allow the user to show his name in blog posts
          </p>
        </div>
        <!-- /.form-group -->

        <h3 class="control-sidebar-heading">Chat Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Show me as online
            <input type="checkbox" class="pull-right" checked>
          </label>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Turn off notifications
            <input type="checkbox" class="pull-right">
          </label>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Delete chat history
            <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
          </label>
        </div>
        <!-- /.form-group -->
      </form>
    </div>
    <!-- /.tab-pane -->
  </div>
</aside>
<!-- /.control-sidebar -->

resources/views/partials/head.blade.php
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>HelpDesk | {{ $ruta }}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/bower_components/Ionicons/css/ionicons.min.css">
  <!-- fullCalendar -->
  <link rel="stylesheet" href="/bower_components/fullcalendar/dist/fullcalendar.min.css">
  <link rel="stylesheet" href="/bower_components/fullcalendar/dist/fullcalendar.print.min.css" media="print">
  <!-- DataTables -->
  <link rel="stylesheet" href="/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
  <!-- daterange picker -->
  <link rel="stylesheet" href="/bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <!-- Select2 -->
  <link rel="stylesheet" href="/bower_components/select2/dist/css/select2.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
   folder instead of downloading all of them to reduce the load. -->
   <link rel="stylesheet" href="/dist/css/skins/_all-skins.min.css">
   <!-- iCheck for checkboxes and radio inputs -->
   <link rel="stylesheet" href="/plugins/iCheck/all.css">
   
   <script>
    window.Laravel = <?php echo json_encode([
      'csrfToken' => csrf_token(),
      ]); ?>
    </script>
    <style>
    .example-modal .modal {
      position: relative;
      top: auto;
      bottom: auto;
      right: auto;
      left: auto;
      display: block;
      z-index: 1;
    }

    .example-modal .modal {
      background: transparent !important;
    }
  </style>


  <style>
  .loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url('/dist/img/loader.gif') 50% 50% no-repeat rgb(255,255,255);
    opacity: ;
  }
</style>


<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet"
href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"> @yield('head')

<!-- Morris chart -->
<!-- <link rel="stylesheet" href="/bower_components/morris.js/morris.css"> -->
<!-- jvectormap -->
<!-- <link rel="stylesheet" href="/bower_components/jvectormap/jquery-jvectormap.css">-->
<!-- Date Picker -->
<!-- <link rel="stylesheet" href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">-->
<!-- Daterange picker -->
<!-- <link rel="stylesheet" href="/bower_components/bootstrap-daterangepicker/daterangepicker.css">-->
<!-- bootstrap wysihtml5 - text editor -->
<!-- <link rel="stylesheet" href="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">-->



<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->   
</head>

resources/views/partials/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>H</b>D</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Help</b>Desk</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">       
        
        
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">            
              <img src="{{ Storage::url( Auth::user()->avatar) }}" class="user-image" alt="{{ Auth::user()->name }}">
            <span class="hidden-xs">{{ Auth::user()->name_short }}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">              
              <img src="{{ Storage::url( Auth::user()->avatar) }}" class="img-circle" alt="{{ Auth::user()->name }}">              
              <p>
                {{ Auth::user()->name_short }} - {{ Auth::user()->profile_name }}
                <small>Miembro desde - {{ Auth::user()->created_at->format('d/m/Y') }}</small>
              </p>
            </li>
            <!-- Menu Body -->
            
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="/perfil" class="btn btn-default btn-flat">Perfil</a>
              </div>
              <div class="pull-right">
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();"
                class="btn btn-default btn-flat">Cerrar sesion
              </a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>
            </div>
          </li>
        </ul>
      </li>
      <!-- Control Sidebar Toggle Button -->
      
    </ul>
  </div>
</nav>
</header>

resources/views/partials/htmlhead.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>HelpDesk</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="plugins/iCheck/square/blue.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">

  @yield('content')  

  <!-- /.login-box -->

  <!-- jQuery 3 -->
  <script src="bower_components/jquery/dist/jquery.min.js"></script>
  <!-- Bootstrap 3.3.7 -->
  <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <!-- iCheck -->
  <script src="plugins/iCheck/icheck.min.js"></script>
  <script>
    $(function () {
      $('input').iCheck({
        checkboxClass: 'icheckbox_square-blue',
        radioClass: 'iradio_square-blue',
        increaseArea: '20%' // optional
      });
    });
  </script>
</body>
</html>

resources/views/partials/menu.blade.php
<?php
use App\Http\Controllers\Admin\MenuController;

/** @var  $userLogeado Usuario actual en el sistema */
$userLogeado = Auth::user()->profile_id;
/** @var  $menu Menu asignado al rol */
$menu = MenuController::construirMenu(0, $userLogeado);


?>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">        
        <img src="{{ Storage::url( Auth::user()->avatar) }}" class="img-circle" alt="{{ Auth::user()->name }}" title="Imagen de perfil">
      </div>
      <div class="pull-left info">
        <br>
        <p><a href="/perfil">{{ Auth::user()->name_short }}</a></p>        
      </div>
    </div>
    
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">Elegir Empresa</li>
      <li class="form-inline">
        <a>
          <i class="fa fa-list-alt"></i>
          <span>
            <select id="list-of-projects" class="form-control select2" style="width: 85%;">
              <option value="0">Seleccione un proyecto</option>
              @foreach (auth()->user()->list_of_projects as $project)
              <option value="{{ $project->id }}" 
                @if($project->id == auth()->user()->selected_project_id)
                selected 
                @endif>
                {{ $project->name }}
              </option>
              @endforeach
            </select>
          </span>
        </a>
      </li>            
      <li class="header">Menú Principal</li>
      @if(auth()->check())
      <li @if(request()->is('home')) class="active" @endif>
        <a href="/home">
          <i class="fa fa-dashboard"></i>
          <span>Panel Principal</span>
        </a>
      </li>
      <!--
      <li @if(request()->is('correo')) class="active" @endif>
        <a href="/correo">
          <i class="fa fa-inbox"></i>
          <span>Bandeja de entrada</span>
        </a>
      </li>
    -->
      <!-- Llamamos a la variable que contiene el menú -->
      {!! $menu !!}
      @endif               
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>