routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('Panel Principal');
Route::get('/seleccionar/proyecto/{id}', 'HomeController@selectProject');

Route::group(['middleware' => ['auth','permisos']], function(){
	
	//User Profile
	Route::get('/perfil', 'Admin\UserController@profile')->name('Perfil de Usuario');
    Route::post('perfil/{id}', 'Admin\UserController@update_perfil');
	
	//Permits
	Route::get('/permisos', 'Admin\PermitController@index')->name('Permisos');    
	Route::post('/permisos', 'Admin\PermitController@store')->name('permisos.store');
	
	Route::get('/permisos/{id}', 'Admin\PermitController@edit')->name('Editar permisos');
    Route::post('/permisos/{id}', 'Admin\PermitController@update')->name('permisos.update');    

	//Incidents
	//See Incidents
	Route::get('/ver', 'IncidentController@index')->name('Ver incidencias');
	Route::post('/ver/reasignar', 'IncidentController@reassign')->name('ver.reasignar');

	//Report Incident
	Route::get('/reportar', 'IncidentController@create')->name('Reportar incidencias');    
	Route::post('/reportar', 'IncidentController@store')->name('reportar.store');
	//Edit Incident
	Route::get('/incidencia/{id}/editar', 'IncidentController@edit')->name('Editar incidencia');
	Route::post('/incidencia/{id}/editar', 'IncidentController@update')->name('incidencia.update');
	
	//See incident
	Route::get('/ver/{id}', 'IncidentController@show')->name('Ver Detalles de la Incidencia');	
	Route::post('/ver/asignar', 'IncidentController@assign')->name('ver.assign');	
	Route::get('/incidencia/{id}/atender', 'IncidentController@take')->name('ver.take');
	Route::get('/incidencia/{id}/resolver', 'IncidentController@solve')->name('ver.solve');
	Route::get('/incidencia/{id}/abrir', 'IncidentController@open')->name('ver.open');
	Route::get('/incidencia/{id}/derivar', 'IncidentController@nextLevel')->name('ver.nextLevel');

	//Messages
	Route::post('/mensajes',[
		'as' => 'mensajes.store',
		'uses' => 'MessageController@store'
	]);
	/*
	//Calendar Asignament
	Route::get('/calendario', function () {
		return view('calendar');
	});
	*/

	//statistics charts
	Route::get('/estadisticas', 'GraficasController@index')->name('Reportes y Estadisticas');
	Route::get('/estadisticas/{anio}/{mes}', 'GraficasController@registros_mes')->name('reportes.anio.mes');
	Route::get('/estadisticas/incidencias/{anio}/{mes}', 'GraficasController@total_incidencias')->name('estadisticas.incidencias');
	Route::get('/estadisticas/modulos/{anio}/{mes}', 'GraficasController@total_modulos')->name('estadisticas.modulos');

	//User
	Route::get('/usuarios', [
	    'as' => 'Creación de usuarios',
        'uses' => 'Admin\UserController@index'
    ]);
	Route::post('/usuarios', [
		'as' => 'usuarios.store',
		'uses' => 'Admin\UserController@store'
	]);

	Route::get('/usuarios/{id}', [
		'as' => 'Editar usuario',
		'uses' => 'Admin\UserController@edit'
	]);	
	Route::post('/usuarios/{id}', [
		'as' => 'usuarios.update',
		'uses' => 'Admin\UserController@update'
	]);
	Route::get('/usuarios/{id}/eliminar', [
		'as' => 'usuarios.delete',
		'uses' => 'Admin\UserController@delete'
	]);

	//Profiles
	Route::get('/perfiles', [
	    'as' => 'Roles de usuarios',
        'uses' => 'Admin\ProfileController@index'
    ]);
	Route::post('/perfiles', [
		'as' => 'perfiles.store',
		'uses' => 'Admin\ProfileController@store'
	]);
	Route::post('/perfiles/editar', [
		'as' => 'perfiles.update',
		'uses' => 'Admin\ProfileController@update'
	]);
	Route::get('/perfiles/{id}/eliminar', [
		'as' => 'perfiles.delete',
		'uses' => 'Admin\ProfileController@delete'
	]);
	Route::get('/perfiles/{id}/restaurar', [
		'as' => 'perfiles.restore',
		'uses' => 'Admin\ProfileController@restore'
	]);

	//Menu
	Route::get('/opciones', [
	    'as' => 'Menú',
        'uses' => 'Admin\MenuController@index'
    ]);
	Route::post('/opciones', [
		'as' => 'opciones.store',
		'uses' => 'Admin\MenuController@store'
	]);
	Route::get('/opciones/{id}', [
		'as' => 'Editar opciones',
		'uses' => 'Admin\MenuController@edit'
	]);
	Route::post('/opciones/{id}', [
		'as' => 'opciones.update',
		'uses' => 'Admin\MenuController@update'
	]);
	Route::get('/opciones/{id}/eliminar', [
		'as' => 'opciones.delete',
		'uses' => 'Admin\MenuController@delete'
	]);
	Route::get('/opciones/hijos/{id}', [
		'as' => 'opciones.gethijos',
		'uses' => 'Admin\MenuController@gethijos'
	]);

	//Project
	Route::get('/proyectos', [
	    'as' => 'Proyectos',
        'uses' => 'Admin\ProjectController@index'
    ]);
	Route::post('/proyectos', [
		'as' => 'proyectos.store',
		'uses' => 'Admin\ProjectController@store'
	]);
	Route::get('/proyectos/{id}', [
		'as' => 'Editar proyectos',
		'uses' => 'Admin\ProjectController@edit'
	]);
	Route::post('/proyectos/{id}', [
		'as' => 'proyectos.update',
		'uses' => 'Admin\ProjectController@update'
	]);
	Route::get('/proyectos/{id}/eliminar', [
		'as' => 'proyectos.delete',
		'uses' => 'Admin\ProjectController@delete'
	]);
	Route::get('/proyectos/{id}/restaurar', [
		'as' => 'proyectos.restore',
		'uses' => 'Admin\ProjectController@restore'
	]);

	//Category
	Route::post('/categorias', [
		'as' => 'categorias.store',
		'uses' => 'Admin\CategoryController@store'
	]);
	Route::post('/categorias/editar', [
		'as' => 'categorias.update',
		'uses' => 'Admin\CategoryController@update'
	]);
	Route::get('/categorias/{id}/eliminar', [
		'as' => 'categorias.delete',
		'uses' => 'Admin\CategoryController@delete'
	]);	

	//Level
	Route::post('/niveles', [
		'as' => 'niveles.store',
		'uses' => 'Admin\LevelController@store'
	]);
	Route::post('/niveles/editar', [
		'as' => 'niveles.update',
		'uses' => 'Admin\LevelController@update'
	]);
	Route::get('/niveles/{id}/eliminar', [
		'as' => 'niveles.delete',
		'uses' => 'Admin\LevelController@delete'
	]);

	//Project-User
	Route::post('/proyecto-usuario', [
		'as' => 'proyectos_usuario.store',
		'uses' => 'Admin\ProjectUserController@store'
	]);
	Route::get('/proyecto-usuario/{id}/eliminar', [
		'as' => 'proyectos_usuario.delete',
		'uses' => 'Admin\ProjectUserController@delete'
	]);
	/**
	//Config
	Route::get('/config', [
		'as' => 'config.index',
		'uses' => 'ConfigController@index'
	]);	**/
});


Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('social.auth');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
/**
 * Módelo que contiene los datos de los menús
 * Class Menu
 * @package App
 */
class Menu extends Model
{
    public static $rules = [
            'name' => 'min:3|required',
            'src' => 'min:1|required',
           // 'orden' => 'required|unique:foods_menu,orden,'.$this->route->getParameter('menu'),
            'orden' => 'required',
            'id_padre' => 'required',
            'as' => 'required'

        ];
    public static $messages = [
        'name.required' => 'Es necesario ingresar un nombre para la opcion.',
        'name.min' => 'El nombre es demasiado corto.',
        'src.unique' => 'No pueden existir dos menús con la misma ruta',
        'orden.unique' => 'No pueden existir dos menús con el mismo orden',
        'as.required' => 'Es necesario ingresar el nombre de la ruta'        
    ];
    protected $table = 'menu';
    protected $fillable = ['id', 'name', 'src', 'orden', 'icon', 'id_padre', 'as'];
    /**
     * Un menú solo tiene un padre
     * relación 1:N
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function padre()
    {
        return $this->belongsTo('App\Menu','id_padre');
    }
	/**
    public function scopeSearch($query, $buscar)
    {
        return $query->where('nombre', 'LIKE', "%$buscar%")
            ->orWhere('src', 'LIKE', "%$buscar%");
    }
    */
    
    public function getNamePadreAttribute()
    {
        if ($this->padre)
            return $this->padre->name;
    }
    
}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Menu;
use App\Permit;

class MenuController extends Controller
{
    /**
     * Función para retornar todos los elementos de la tabla de los menús
     * @return mixed
     */
    public function index()
    {
        /**
         * Consultamos los menús que tengan un enlace padre con id>=0,
         * ya que el enlace de donde heredan todos será el id = 0 y este tendrá como padre -1
         */
        $menus = Menu::all();
        $maxOrden = $menus->max('orden');        
        return view('admin.menu.index')->with(compact('menus','maxOrden'));
    }
    /**
     * Funcion que me permite almacenar las entradas de un menu
     * @param Request $request 
     * @return type
     */
    public function store(Request $request)
	{
		
		$this->validate($request, Menu::$rules, Menu::$messages);

		$menu = new Menu();
		$menu->name = $request->input('name');
		$menu->src = $request->input('src');
		$menu->orden = $request->input('orden');
		$menu->icon = $request->input('icon');
		$menu->id_padre = $request->input('id_padre');
        $menu->as = $request->input('as');
		if ($menu->icon == '') {
            $menu->icon = 'fa fa-circle-o';
        }
        $menu->save();		
		
		return back()->with('notification', 'La nueva opción ha sido registrada exitosamente.');
	}

	/**
	 * Función que retorna una vista para editar un menú
     * @param $id el id del menú
     * @return mixed
     */
    public function edit($id)
    {
        /** @var  $menu Menu que es el padre */
        $menu = Menu::find($id);
        $menus = Menu::all();
        


        $maxOrden = $menu->max('orden');
        return view('admin.menu.edit')->with(compact('maxOrden','menu','menus'));
    }
	/**
     * Función que actualiza un menú en la base de datos
     * @param MenuRequest $request los datos que se van a actualizar
     * @param $id el id del menú
     * @return mixed
     */
    public function update(Request $request, $id)
    {
        
        Menu::find($id)->update($request->all());
       
        return back()->with('notification', 'Se ha actualizado el menú correctamente.');
        
    }

	/**
     * Función que elimina un menú de la base de datos
     * @param $id el id del menú
     * @return mixed
     */	
    public function delete($id)
    {
        /**
         * Consultamos si el id que será eliminado tiene enlaces hijos,
         * en caso de que los tenga no se podrá eliminar
         */
        $numeroHijos = self::tieneHijos($id);

        if (!$numeroHijos) {

            Menu::find($id)->delete();
            return back()->with('notification', 'Se ha eliminado el menú correctamente.');
            
        } else {
            
            Menu::find($id);
            return back()->with('notification', 'No puede ser eliminado ya que está relacionado con otros enlaces.');
            
        }
    }

	/**
     * Función para consultar si un id está relacionado con otros enlaces
     * @param $id_padre
     * @return bool
     */
    static private function tieneHijos($id_padre)
    {
        $hay = false;

        $menu = Menu::where('id_padre', $id_padre)->count();

        if ($menu > 0) {
            $hay = true;
        }

        return $hay;
    }

	/**
     * Mètodo para construir el menù de acuerdo a los permisos del rol de cada usuario
     * @param int $id_padre el menù padre
     * @param int $id el usuario que solicita el menù
     * @return string
     */
    static public function construirMenu($id_padre = 0, $id = 0)
    {

        $etiquetaMenu = '';
        
        $menus = Menu::where('id_padre', $id_padre)->get();
        $totalMenus = $menus->count();

        if ($totalMenus > 0) {
            $etiquetaMenu .= '';

            foreach ($menus As $menu) {

                /**
                 * AVISO IMPORTANTE
                 */
                /** Esta variable debe ir en false, se cambia temporalmente */
                $tienePermiso = false;

                /**
                 * Comprobamos si el id que se recibe no es null, y cambiamos el valor de la variable
                 * @param $tienePermiso para marcar el checkbox que tiene el permiso
                 */
                if ($id != null) {

                    $permisos = Permit::where('menu_id', $menu->id)
                        ->where('profile_id', $id);

                    $totalPermiso = $permisos->count();

                    if ($totalPermiso > 0) {
                        $tienePermiso = true;
                    }
                }


                /**
                 * Consultamos si el menú que se está creando tiene hijos para crear en enlace
                 * true si tiene hijos, false si no tiene
                 */
                $numeroHijos = self::tieneHijos($menu->id);


                if ($numeroHijos && $tienePermiso && $menu->show == 1 ) {

                    $etiquetaMenu .= '<li class="treeview">';
                    $etiquetaMenu .= '<a href="' . url($menu->src) . '">';
                    $etiquetaMenu .= '<i class="' . $menu->icon . ' "></i>';
                    $etiquetaMenu .= '<span>' . $menu->name . '</span>';
                    $etiquetaMenu .= '<i class="fa fa-angle-left pull-right"></i>';
                    $etiquetaMenu .= '</a>';

                    $etiquetaMenu .= '<ul class="treeview-menu">';
                    $etiquetaMenu .= self::construirMenu($menu->id, $id);
                    $etiquetaMenu .= '</ul>';

                    $etiquetaMenu .= '</li>';
                } else if ($tienePermiso && $menu->show == 1) {
                    $etiquetaMenu .= '<li>';
                    $etiquetaMenu .= '<a href="' . url($menu->src) . '">';
                    $etiquetaMenu .= '<i class="' . $menu->icon . '"></i>';
                    $etiquetaMenu .= '<span>' . $menu->name . '</span>';
                    $etiquetaMenu .= '</a>';
                    $etiquetaMenu .= '</li>';
                }
            }

        }
        return $etiquetaMenu;
    }

	 /**
     * Función para retornar el menú completo
     * esta función se crea inicialmente para la creación y actualización de permisos
     * @param int $id_padre
     * @param int $id id del rol que se va a consultar los permisos, para la creación de un permiso se envia este campo como vacio
     * @return string
     */
    static public function construirMenuCompleto($id_padre = 0, $id)
    {

        $etiquetaMenu = '';        
        $menus = Menu::where('id_padre', $id_padre)->get();
        $totalMenus = $menus->count();

        if ($totalMenus > 0) {
            $etiquetaMenu .= '';

            foreach ($menus As $menu) {

                $marcar = '';

                /**
                 * Comprobamos si el id que se recibe no es null, y cambiamos el valor de la variable
                 * @param $marcar para marcar el checkbox que tiene el permiso
                 */
                if ($id != null) {

                    $permisos = Permit::where('menu_id', $menu->id)->where('profile_id', $id);

                    $totalPermiso = $permisos->count();

                    if ($totalPermiso > 0) {
                        $marcar = 'checked';
                    }
                }

                /**
                 * Consultamos si el menú que se está creando tiene hijos para crear en enlace
                 * true si tiene hijos, false si no tiene
                 */
                $numeroHijos = self::tieneHijos($menu->id);
                
                if ($numeroHijos) {                   

                    $etiquetaMenu .= '<ul class="autoCheckbox">';
                    $etiquetaMenu .= '<li class="">';
                    $etiquetaMenu .= '<a href="">';
                    $etiquetaMenu .= '<label class="checkbox">';
                    $etiquetaMenu .= '<input type="checkbox" value="' . $menu->id . '" name="menu_id[]" ' . $marcar . ' >&nbsp';
                    $etiquetaMenu .= $menu->name;
                    $etiquetaMenu .= '</label>';
                    $etiquetaMenu .= '</a>';
                    $etiquetaMenu .= '<ul class="autoCheckbox">';
                    $etiquetaMenu .= self::construirMenuCompleto($menu->id, $id);
                    $etiquetaMenu .= '</ul>';
                    $etiquetaMenu .= '</li>';
                    $etiquetaMenu .= '</ul>';
                } else {
                    $etiquetaMenu .= '<ul class="autoCheckbox">';
                    $etiquetaMenu .= '<li class="treeview">';
                    $etiquetaMenu .= '<a href="#">';
                    $etiquetaMenu .= '<label class="checkbox">';
                    $etiquetaMenu .= '<input type="checkbox" value="' . $menu->id . '" name="menu_id[]" ' . $marcar . ' >&nbsp';
                    $etiquetaMenu .= $menu->name;
                    $etiquetaMenu .= '</label>';
                    $etiquetaMenu .= '</a>';
                    $etiquetaMenu .= '</li>';
                    $etiquetaMenu .= '</ul>';
                }
                

            }
        }
        return $etiquetaMenu;
    }

	/**
     * Retorna el orden máximo que tienen los hijos
     * @param $id
     * @return mixed
     */
    public function getHijos($id)
    {
        return Menu::where('id_padre', $id)->max('orden');
    }
}

resources/views/admin/menu/edit.blade.php
@extends('layouts.app')

@section('content')

<section class="content-header">
  <h1>
    Menú
    <small>Editar Menú</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a><i class="fa fa-user-circle"></i> Administración</a></li>
    <li><a href="/opciones"><i class="fa fa-bars"></i> Menú</a></li>
    <li class="active">Editar Menú</li>
  </ol>
</section>
<section class="content">
  <div class="panel-body">
    @if (session('notification'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-check"></i>
      {{ session('notification') }}        
    </div>      
    @endif
    @if (count($errors) > 0)
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><i class="icon fa fa-ban"></i> Alert!</h4>
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>  
    </div>      
    @endif  
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Editar Menú</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <form action="" method="POST">
        {{ csrf_field() }}
        <div class="box-body">
          <div class="form-group">
            <label>Padre</label>
            
            <select name="id_padre" class="form-control select2" style="width: 100%;">
              <option value="">Seleccione una opción</option>
              @foreach ($menus as $lista)
              <option value="{{ $lista->id }}" @if($lista->id) selected @endif>
                {{ $lista->id }} - 
                {{ $lista->name }} -                           
                ( {{ $lista->name_padre }} ) - 
                {{ $lista->src }}
              </option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="name">Nombre</label>
            <input type="text" name="name" class="form-control" value="{{ old('name', $menu->name) }}">
          </div>
          <div class="form-group">
            <label for="src">Ruta</label>
            <input type="text" name="src" class="form-control" value="{{ old('src', $menu->src) }}">
          </div>
          <div class="form-group">
            <label for="as">Nombre de la ruta</label>
            <input type="text" name="as" class="form-control" value="{{ old('as', $menu->as) }}">
          </div>
          <div class="form-group">
            <label for="orden">Orden</label>
            <input type="text" name="orden" class="form-control" value="{{ old('orden', $menu->orden) }}">
            Orden máximo generado: <label id="label-max-orden">{{$maxOrden}}</label>
          </div>
          <div class="form-group">
            <label for="icon">Icono</label>
            <input type="text" name="icon" class="form-control" value="{{ old('icon', $menu->icon) }}">
            <p>Para mas iconos visitar: <a href="http://fontawesome.io/icons/#web-application" target="blank">Font Awesome</a> </p>
          </div>

        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button class="btn btn-primary">
            <i class="fa fa-save"></i>
            Guardar Cambios
          </button>
        </div>
      </form>           
    </div>
  </div>
</section>
@endsection
@section('scripts')
<script>
  $("#select-id-padre").change(function () {
    OnselectMaxOrden('select-id-padre', 'label-max-orden', 'opciones/hijos/')
  });

  // Función para poner el maximo orden de un padre
  function OnselectMaxOrden(idSelectPadre, labelHijo, ruta) {

    var selectPadre = document.getElementById(idSelectPadre).value;

    // si no se ha seleccionado nada, entonces dejamos el label vacio
    if (!selectPadre) {
      $('#' + labelHijo).html('-');
      return;
    }

    //Función AJAX que cambia los valores de la lista dinamicamente
    $.get(ruta + selectPadre, function (data) {

      //variable que contiene el html que se pondrá en el label
      var html_select = data;

      if (data == '') {
        html_select = '0';
      }

      // cambiamos el html del label
      $('#' + labelHijo).html(html_select)
    });
  }
</script>
@endsection

resources/views/admin/menu/index.blade.php
@extends('layouts.app')

@section('content')

<section class="content-header">
  <h1>
    Menú
    <small>Crear Opciones</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a><i class="fa fa-user-circle"></i> Administración</a></li>
    <li class="active">Menú</li>
  </ol>
</section>
<section class="content">
  <div class="panel-body">
    @if (session('notification'))
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-check"></i>
      {{ session('notification') }}        
    </div>      
    @endif
    @if (count($errors) > 0)
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><i class="icon fa fa-ban"></i> Alert!</h4>
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>  
    </div>      
    @endif
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Crear Opciones</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <form action="" method="POST">
        {{ csrf_field() }}
        <div class="box-body">
          <div class="form-group">
            <label>Padre</label>
            <select name="id_padre" id="select-id-padre" class="form-control select2" style="width: 100%;">
              <option value="">Seleccione una opción</option>
              @foreach ($menus as $menu)

              <option value="{{ $menu->id }}">
                {{ $menu->id }} - 
                {{ $menu->name }} - 
                ( {{ $menu->name_padre }} ) - 
                {{ $menu->src }}
              </option>
              
              @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="name">Nombre</label>
            <input type="text" name="name" class="form-control" value="{{ old('name') }}">
          </div>
          <div class="form-group">
            <label for="src">Ruta</label>
            <input type="text" name="src" class="form-control" value="{{ old('src') }}">
          </div>
          <div class="form-group">
            <label for="as">Nombre de la ruta</label>
            <input type="text" name="as" class="form-control" value="{{ old('as') }}">
          </div>
          <div class="form-group">
            <label for="orden">Orden</label>
            <input type="text" name="orden" class="form-control" value="{{ old('orden') }}">
            Orden máximo generado: <label id="label-max-orden" />   
          </div>
          <div class="form-group">
            <label for="icon">Icono</label>
            <input type="text" name="icon" class="form-control" value="{{ old('icon') }}">
            <p>Para mas iconos visitar: <a href="http://fontawesome.io/icons/#web-application" target="blank">Font Awesome</a> </p>
          </div>

        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button class="btn btn-primary">
            <i class="fa fa-plus-circle"></i>
          Registrar nueva opción</button>
        </div>
      </form>
      <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>ID</th>
              <th>Icono</th>
              <th>Nombre</th>
              <th>Ruta</th>
              <th>Nombre de la ruta</th>
              <th>Orden</th>
              <th>Padre</th>
              <th>Opciones</th> 
            </tr>                            
          </thead>
          <tbody>
            @foreach ($menus as $menu)
            @if($menu->id_padre >= 0)                            
            <tr>
              <td>{{ $menu->id }}</td>
              <td style="text-align:center"><i class="{{ $menu->icon }}"></i></td>
              <td>{{ $menu->name }}</td>
              <td>{{ $menu->src }}</td>
              <td>{{ $menu->as }}</td>
              <td>{{ $menu->orden }}</td>
              <td>{{ $menu->name_padre }}</td>
              <td style="text-align:center">
                <a href="/opciones/{{ $menu->id }}" class="btn btn-sm btn-primary" title="Editar">
                  <i class="fa fa-edit"></i>
                </a>
                <a href="/opciones/{{ $menu->id }}/eliminar" class="btn btn-sm btn-danger" title="Dar de baja">
                  <i class="fa fa-trash"></i>
                </a>                          
              </td>                        
            </tr>
            @endif
            @endforeach                      
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
@endsection
@section('scripts')
<script>
  $("#select-id-padre").change(function () {
    OnselectMaxOrden('select-id-padre', 'label-max-orden', 'opciones/hijos/')
  });

  // Función para poner el maximo orden de un padre
  function OnselectMaxOrden(idSelectPadre, labelHijo, ruta) {

    var selectPadre = document.getElementById(idSelectPadre).value;

    // si no se ha seleccionado nada, entonces dejamos el label vacio
    if (!selectPadre) {
      $('#' + labelHijo).html('-');
      return;
    }

    //Función AJAX que cambia los valores de la lista dinamicamente
    $.get(ruta + selectPadre, function (data) {

      //variable que contiene el html que se pondrá en el label
      var html_select = data;

      if (data == '') {
        html_select = '0';
      }

      // cambiamos el html del label
      $('#' + labelHijo).html(html_select)
    });
  }
</script>
@endsection